### PR TITLE
Couple of fixes and additions (SSL, options.conf)

### PR DESCRIPTION
**Pull request by dachinat**
There fix for couple of issues in PR, also few additions:

* `directadmin_use_ssl` - *Boolean* - Sets `SSL=1` in directadmin config
* `directadmin_ca_key`, `directadmin_ca_cert` - *String* - Certificate file paths
* `directadmin_use_ssl_in_httpd`- *Boolean* - Use certificates outside `DA` (:2222) or not
* `directadmin_force_update_options` - *Boolean* - Process and make changes introduced in `options.conf.j2` template or not (May take a time)

There is also a change of a way DA installation is checked. Request check would succeed if server was off for maintenance. Here we check by looking for existence of configuration file.

### CODE REVIEW

**Comment by hyperized** [comment]
@dachinat Thank you for this PR. I will be back in town tomorrow so I will have a detailed look. In the meantime, can you avoid duplication of the whole role in the test folder?

**Comment by dachinat** [comment]
@hyperized 
I've cleaned test/ directory.

Also added support for replacing default `server.crt` `server.key` and `server.ca`

**Comment by Wouter0100** [comment]
@hyperized any change you could look into merging this? Seems to be useful, although may using an array for the options like SSL would be more useful

**Comment by hyperized** [comment]
@Wouter0100 Which particular issues would you like to see fixed? I haven't heard back from @dachinat since my review and I cannot accept all of the proposed changes as is. I can update the code where you need. Can you perhaps create an issue for this?

**Comment by Wouter0100** [comment]
Hmm - but he did reply? uhh :smile: But I'll make some issues ;)!

**Comment by hyperized** [comment]
@Wouter0100 thanks for pointing that out, the review was stuck on pending .. I never realized because it showed in-line in the conversation on my screen.

**Comment by hyperized** [comment]
I'm going to go ahead and close this PR since there have been no updates or any movement towards the provided feedback. I'll see what I can pick up feature wise in a new release.

**Pull request closed without merging**
